apiVersion: apps/v1
kind: Deployment
metadata:
  name: fromdynaomodb2
spec:
  replicas: 2
  selector:
    matchLabels:
      app: fromdynaomodb2
  template:
    metadata:
      labels:
        app: fromdynaomodb2
    spec:
      containers:
        - name: app
          image: gcr.io/fromdynaomodb2/fromdynaomodb_image2:v1
          imagePullPolicy: Always
