#CICD done
on:
  push:
    branches:
      - main

env:
  PROJECT_ID: ${{ secrets.FROMDYNAOMODB_PROJECT }}
  CLUSTER: mycluster
  ZONE: us-central1
  DEPLOYMENT_NAME: fromdynaomodb2
  IMAGE: fromdynaomodb2_image
  TAG: v1


jobs:
  setup-build-publish-deploy:
    name: Setup Build Publish Deploy
    runs-on: ubuntu-latest

    steps:

      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Setup Google Cloud CLI
        uses: GoogleCloudPlatform/github-actions/setup-gcloud@0.1.3
        env:
          ACTIONS_ALLOW_UNSECURE_COMMANDS: true
        with:
          service_account_key: ${{secrets.FROMDYNAOMODB_KEY}}
          project_id: ${{secrets.FROMDYNAOMODB_PROJECT}}

      - name: Configure Docker in GKE
        run: gcloud --quiet auth configure-docker

      - name: Get Credentials GKE
        run: gcloud container clusters get-credentials "$CLUSTER" --zone "$ZONE"

      # Build the Docker image
      - name: Build Docker Image GCR
        run: |-
          docker build --tag gcr.io/fromdynaomodb2/fromdynaomodb_image2:v1 .

      - name: Publish Docker Image to GCR
        run: |-
          docker push gcr.io/fromdynaomodb2/fromdynaomodb_image2:v1

      - name: Install Gcloud Component
        run: |-
          gcloud components install gke-gcloud-auth-plugin

      - name: Deploy Image to GKE cluster
        run: |-
          kubectl apply -f deployment.yaml
          kubectl apply -f service.yaml
          kubectl rollout restart deployment $DEPLOYMENT_NAME
          kubectl get services -o wide
